---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: i want to cxcute direct linux command 
    command: hostname -f
    register: myfirsttaskresults 
  - name: i want to debug myfirst task result
    debug: 
      msg: "{{myfirsttaskresults}}"